%YAML:1.0
---
# width and height of the original image in pixels
image_height: 480
image_width: 640

# width and height in pixels of segmentation network output
# (when given the above input)
seg_height: 11
seg_width: 54
#seg_height: 480
#seg_width: 640

# the width and height of the image representing a top-down view of the real world
costmap_height: 20
costmap_width: 30

# the number of meters per pixel (currently 0.05)
m_per_pixel: 5.00e-02
#m_per_pixel: 0.1

# file path indicating where to write the file
homography_file_path: "/home/alex/src/catkin_ws/src/robaka-ros/config/semantic-segmentation/homography.xml"

# file path pointing to sample segmentation data
#seg_data_path: "/home/nvidia/deep_nav_layers/calibrate_homography/segmentation-output.jpg"
